import "./globals.css";
import AuthProvider from "./Providers/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
